accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
  - name: allowed1
    coins: ["10000token", "100000000stake"]
    mnemonic: "excuse stuff pig actress entire carbon fossil similar enact crime desert essay suspect tortoise hand valid trophy suspect tuna deliver prevent biology island face"
  - name: allowed2
    coins: ["10000token", "100000000stake"]
    mnemonic: "crucial beyond salt daughter income cheese jeans retreat tobacco illness educate tiny more devote elder cheese more crush label field question timber rent video"
  - name: allowed3
    coins: ["10000token", "100000000stake"]
    mnemonic: "camera board claw toilet under unknown asset bag obey orphan together attract spell fog night offer curtain visit soda wave candy parade share frame"
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
